-- Script untuk menambahkan data sample telur ke database
-- Jalankan script ini setelah database schema sudah dibuat

USE db_smarternak;

-- Tambahkan data telur sample untuk hari ini
INSERT INTO egg_scans (egg_code, quality, image, scanned_at) VALUES
-- Telur hari ini
(CONCAT('EGG-', DATE_FORMAT(CURDATE(), '%Y%m%d'), '-0001'), 'good', NULL, CONCAT(CURDATE(), ' 07:30:00')),
(CONCAT('EGG-', DATE_FORMAT(CURDATE(), '%Y%m%d'), '-0002'), 'good', NULL, CONCAT(CURDATE(), ' 07:35:00')),
(CONCAT('EGG-', DATE_FORMAT(CURDATE(), '%Y%m%d'), '-0003'), 'bad', NULL, CONCAT(CURDATE(), ' 07:40:00')),
(CONCAT('EGG-', DATE_FORMAT(CURDATE(), '%Y%m%d'), '-0004'), 'good', NULL, CONCAT(CURDATE(), ' 07:45:00')),
(CONCAT('EGG-', DATE_FORMAT(CURDATE(), '%Y%m%d'), '-0005'), 'good', NULL, CONCAT(CURDATE(), ' 07:50:00')),
(CONCAT('EGG-', DATE_FORMAT(CURDATE(), '%Y%m%d'), '-0006'), 'good', NULL, CONCAT(CURDATE(), ' 07:55:00')),
(CONCAT('EGG-', DATE_FORMAT(CURDATE(), '%Y%m%d'), '-0007'), 'bad', NULL, CONCAT(CURDATE(), ' 08:00:00')),
(CONCAT('EGG-', DATE_FORMAT(CURDATE(), '%Y%m%d'), '-0008'), 'good', NULL, CONCAT(CURDATE(), ' 08:05:00')),
(CONCAT('EGG-', DATE_FORMAT(CURDATE(), '%Y%m%d'), '-0009'), 'good', NULL, CONCAT(CURDATE(), ' 08:10:00')),
(CONCAT('EGG-', DATE_FORMAT(CURDATE(), '%Y%m%d'), '-0010'), 'good', NULL, CONCAT(CURDATE(), ' 08:15:00')),
(CONCAT('EGG-', DATE_FORMAT(CURDATE(), '%Y%m%d'), '-0011'), 'good', NULL, CONCAT(CURDATE(), ' 08:20:00')),
(CONCAT('EGG-', DATE_FORMAT(CURDATE(), '%Y%m%d'), '-0012'), 'bad', NULL, CONCAT(CURDATE(), ' 08:25:00')),
(CONCAT('EGG-', DATE_FORMAT(CURDATE(), '%Y%m%d'), '-0013'), 'good', NULL, CONCAT(CURDATE(), ' 08:30:00')),
(CONCAT('EGG-', DATE_FORMAT(CURDATE(), '%Y%m%d'), '-0014'), 'good', NULL, CONCAT(CURDATE(), ' 08:35:00')),
(CONCAT('EGG-', DATE_FORMAT(CURDATE(), '%Y%m%d'), '-0015'), 'good', NULL, CONCAT(CURDATE(), ' 08:40:00')),

-- Telur kemarin
(CONCAT('EGG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 1 DAY), '%Y%m%d'), '-0001'), 'good', NULL, CONCAT(DATE_SUB(CURDATE(), INTERVAL 1 DAY), ' 07:30:00')),
(CONCAT('EGG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 1 DAY), '%Y%m%d'), '-0002'), 'good', NULL, CONCAT(DATE_SUB(CURDATE(), INTERVAL 1 DAY), ' 07:35:00')),
(CONCAT('EGG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 1 DAY), '%Y%m%d'), '-0003'), 'good', NULL, CONCAT(DATE_SUB(CURDATE(), INTERVAL 1 DAY), ' 07:40:00')),
(CONCAT('EGG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 1 DAY), '%Y%m%d'), '-0004'), 'bad', NULL, CONCAT(DATE_SUB(CURDATE(), INTERVAL 1 DAY), ' 07:45:00')),
(CONCAT('EGG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 1 DAY), '%Y%m%d'), '-0005'), 'good', NULL, CONCAT(DATE_SUB(CURDATE(), INTERVAL 1 DAY), ' 07:50:00')),
(CONCAT('EGG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 1 DAY), '%Y%m%d'), '-0006'), 'good', NULL, CONCAT(DATE_SUB(CURDATE(), INTERVAL 1 DAY), ' 07:55:00')),
(CONCAT('EGG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 1 DAY), '%Y%m%d'), '-0007'), 'good', NULL, CONCAT(DATE_SUB(CURDATE(), INTERVAL 1 DAY), ' 08:00:00')),
(CONCAT('EGG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 1 DAY), '%Y%m%d'), '-0008'), 'good', NULL, CONCAT(DATE_SUB(CURDATE(), INTERVAL 1 DAY), ' 08:05:00')),
(CONCAT('EGG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 1 DAY), '%Y%m%d'), '-0009'), 'bad', NULL, CONCAT(DATE_SUB(CURDATE(), INTERVAL 1 DAY), ' 08:10:00')),
(CONCAT('EGG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 1 DAY), '%Y%m%d'), '-0010'), 'good', NULL, CONCAT(DATE_SUB(CURDATE(), INTERVAL 1 DAY), ' 08:15:00')),

-- Telur 2 hari lalu
(CONCAT('EGG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 2 DAY), '%Y%m%d'), '-0001'), 'good', NULL, CONCAT(DATE_SUB(CURDATE(), INTERVAL 2 DAY), ' 07:30:00')),
(CONCAT('EGG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 2 DAY), '%Y%m%d'), '-0002'), 'good', NULL, CONCAT(DATE_SUB(CURDATE(), INTERVAL 2 DAY), ' 07:35:00')),
(CONCAT('EGG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 2 DAY), '%Y%m%d'), '-0003'), 'good', NULL, CONCAT(DATE_SUB(CURDATE(), INTERVAL 2 DAY), ' 07:40:00')),
(CONCAT('EGG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 2 DAY), '%Y%m%d'), '-0004'), 'good', NULL, CONCAT(DATE_SUB(CURDATE(), INTERVAL 2 DAY), ' 07:45:00')),
(CONCAT('EGG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 2 DAY), '%Y%m%d'), '-0005'), 'bad', NULL, CONCAT(DATE_SUB(CURDATE(), INTERVAL 2 DAY), ' 07:50:00')),
(CONCAT('EGG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 2 DAY), '%Y%m%d'), '-0006'), 'good', NULL, CONCAT(DATE_SUB(CURDATE(), INTERVAL 2 DAY), ' 07:55:00')),
(CONCAT('EGG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 2 DAY), '%Y%m%d'), '-0007'), 'good', NULL, CONCAT(DATE_SUB(CURDATE(), INTERVAL 2 DAY), ' 08:00:00')),
(CONCAT('EGG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 2 DAY), '%Y%m%d'), '-0008'), 'good', NULL, CONCAT(DATE_SUB(CURDATE(), INTERVAL 2 DAY), ' 08:05:00')),

-- Telur 3 hari lalu
(CONCAT('EGG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 3 DAY), '%Y%m%d'), '-0001'), 'good', NULL, CONCAT(DATE_SUB(CURDATE(), INTERVAL 3 DAY), ' 07:30:00')),
(CONCAT('EGG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 3 DAY), '%Y%m%d'), '-0002'), 'good', NULL, CONCAT(DATE_SUB(CURDATE(), INTERVAL 3 DAY), ' 07:35:00')),
(CONCAT('EGG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 3 DAY), '%Y%m%d'), '-0003'), 'bad', NULL, CONCAT(DATE_SUB(CURDATE(), INTERVAL 3 DAY), ' 07:40:00')),
(CONCAT('EGG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 3 DAY), '%Y%m%d'), '-0004'), 'good', NULL, CONCAT(DATE_SUB(CURDATE(), INTERVAL 3 DAY), ' 07:45:00')),
(CONCAT('EGG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 3 DAY), '%Y%m%d'), '-0005'), 'good', NULL, CONCAT(DATE_SUB(CURDATE(), INTERVAL 3 DAY), ' 07:50:00')),
(CONCAT('EGG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 3 DAY), '%Y%m%d'), '-0006'), 'good', NULL, CONCAT(DATE_SUB(CURDATE(), INTERVAL 3 DAY), ' 07:55:00')),

-- Telur 4 hari lalu
(CONCAT('EGG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 4 DAY), '%Y%m%d'), '-0001'), 'good', NULL, CONCAT(DATE_SUB(CURDATE(), INTERVAL 4 DAY), ' 07:30:00')),
(CONCAT('EGG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 4 DAY), '%Y%m%d'), '-0002'), 'good', NULL, CONCAT(DATE_SUB(CURDATE(), INTERVAL 4 DAY), ' 07:35:00')),
(CONCAT('EGG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 4 DAY), '%Y%m%d'), '-0003'), 'good', NULL, CONCAT(DATE_SUB(CURDATE(), INTERVAL 4 DAY), ' 07:40:00')),
(CONCAT('EGG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 4 DAY), '%Y%m%d'), '-0004'), 'bad', NULL, CONCAT(DATE_SUB(CURDATE(), INTERVAL 4 DAY), ' 07:45:00')),
(CONCAT('EGG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 4 DAY), '%Y%m%d'), '-0005'), 'good', NULL, CONCAT(DATE_SUB(CURDATE(), INTERVAL 4 DAY), ' 07:50:00')),

-- Telur 5 hari lalu
(CONCAT('EGG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 5 DAY), '%Y%m%d'), '-0001'), 'good', NULL, CONCAT(DATE_SUB(CURDATE(), INTERVAL 5 DAY), ' 07:30:00')),
(CONCAT('EGG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 5 DAY), '%Y%m%d'), '-0002'), 'good', NULL, CONCAT(DATE_SUB(CURDATE(), INTERVAL 5 DAY), ' 07:35:00')),
(CONCAT('EGG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 5 DAY), '%Y%m%d'), '-0003'), 'good', NULL, CONCAT(DATE_SUB(CURDATE(), INTERVAL 5 DAY), ' 07:40:00')),
(CONCAT('EGG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 5 DAY), '%Y%m%d'), '-0004'), 'good', NULL, CONCAT(DATE_SUB(CURDATE(), INTERVAL 5 DAY), ' 07:45:00')),

-- Telur 6 hari lalu
(CONCAT('EGG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 6 DAY), '%Y%m%d'), '-0001'), 'good', NULL, CONCAT(DATE_SUB(CURDATE(), INTERVAL 6 DAY), ' 07:30:00')),
(CONCAT('EGG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 6 DAY), '%Y%m%d'), '-0002'), 'bad', NULL, CONCAT(DATE_SUB(CURDATE(), INTERVAL 6 DAY), ' 07:35:00')),
(CONCAT('EGG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 6 DAY), '%Y%m%d'), '-0003'), 'good', NULL, CONCAT(DATE_SUB(CURDATE(), INTERVAL 6 DAY), ' 07:40:00'))

ON DUPLICATE KEY UPDATE quality = VALUES(quality);

-- Tampilkan ringkasan data yang telah ditambahkan
SELECT 
    'Data Summary' as info,
    COUNT(*) as total_eggs_added,
    SUM(CASE WHEN quality = 'good' THEN 1 ELSE 0 END) as good_eggs,
    SUM(CASE WHEN quality = 'bad' THEN 1 ELSE 0 END) as bad_eggs,
    COUNT(DISTINCT DATE(scanned_at)) as days_with_data
FROM egg_scans 
WHERE egg_code LIKE CONCAT('EGG-', DATE_FORMAT(CURDATE(), '%Y%m%d'), '%')
   OR egg_code LIKE CONCAT('EGG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 1 DAY), '%Y%m%d'), '%')
   OR egg_code LIKE CONCAT('EGG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 2 DAY), '%Y%m%d'), '%')
   OR egg_code LIKE CONCAT('EGG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 3 DAY), '%Y%m%d'), '%')
   OR egg_code LIKE CONCAT('EGG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 4 DAY), '%Y%m%d'), '%')
   OR egg_code LIKE CONCAT('EGG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 5 DAY), '%Y%m%d'), '%')
   OR egg_code LIKE CONCAT('EGG-', DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 6 DAY), '%Y%m%d'), '%');

SELECT 'Sample data has been added successfully!' as message; 